name: pamphlets_management
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  url_strategy: ^0.2.0
  url_launcher: ^6.2.2
  universal_html: ^2.2.4
  flutter_iconpicker: 3.3.3
  flex_color_picker: ^3.3.1
  fl_chart: ^0.66.0
  file_picker: ^8.0.0+1
  excel: ^4.0.2
  archive: ^3.4.10
  xml: ^6.5.0
  google_fonts: ^6.1.0
  file_saver: ^0.2.12
  flutter_osm_plugin: ^0.70.4
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10+1
  http: any
  googleapis_auth: ^1.5.0
  flutter_styled_toast: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  flutter_lints: ^3.0.1
  http_mock_adapter: ^0.6.0
  logger: ^2.0.2+1
  faker: ^2.1.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    # Environments files
    - dev.env
    #- .env.prod

  fonts:
    - family: CreteRound
      fonts:
        - asset: fonts/CreteRound-Italic.ttf
        - asset: fonts/CreteRound-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 600
