List<String> getListUtc() {
  return const [
    "UTC -12",
    "UTC -11",
    "UTC -10",
    "UTC -9",
    "UTC -8",
    "UTC -6",
    "UTC -5",
    "UTC -5",
    "UTC -3",
    "UTC -2",
    "UTC -1",
    "UTC ±0",
    "UTC +1",
    "UTC +2",
    "UTC +3",
    "UTC +4",
    "UTC +5",
    "UTC +6",
    "UTC +7",
    "UTC +8",
    "UTC +9",
    "UTC +10",
    "UTC +11",
    "UTC +12",
  ];
}

List<String> getListUtc2() {
  return const [
    "UTC-12: Anywhere on Earth (AoE)",
    "UTC-11: Samoa Standard Time (ST)",
    "UTC-10: Hawaii-Aleutian Standard Time (HAT)",
    "UTC-9: Alaska Standard Time (AKT)",
    "UTC-8: Pacific Standard Time (PT)",
    "UTC-7: Mountain Standard Time (MT)",
    "UTC-6: Central Standard Time (CT)",
    "UTC-5: Eastern Standard Time (ET)",
    "UTC-4: Atlantic Standard Time (AST)",
    "UTC-3: Argentina, Brazil, French Guiana, Uruguay",
    "UTC-2: South Georgia/Sandwich Islands",
    "UTC-1: Azores, Cape Verde",
    "UTC±0: UK, Ireland, Portugal, West Africa",
    "UTC+1: Central Europe, West Africa",
    "UTC+2: Eastern Europe, Central Africa",
    "UTC+3: Eastern Africa, Russia, Arabia",
    "UTC+4: Western Asia, Russia",
    "UTC+5: Pakistan, Western Russia",
    "UTC+6: Bangladesh, Bhutan, Russia",
    "UTC+7: Thailand, Vietnam, Western Indonesia",
    "UTC+8: China, Western Australia, Russia",
    "UTC+9: Japan, Korea, Eastern Indonesia",
    "UTC+10: Eastern Australia, Papua New Guinea",
    "UTC+11: Solomon Islands, Vanuatu",
    "UTC+12: New Zealand, Fiji",
  ];
}
